### ISSUE TITLE
EOFError - end of file reached:

### ISSUE THREAD

**Issue by Shakhboz01** [sass-contrib/sass-embedded-host-ruby#272]
The server gives this error

**Comment by ntkme** [comment]
Please provide your OS version, Ruby version, Rubygems version, and bundler version.

**Comment by ntkme** [comment]
I’m going to close this as there isn’t enough information. However, this is extremely likely to be one of the two well known issues that none of them are bugs in this library:

1. Linux distributions’ libc being too old. E.g. If you’re on a super old Redhat/CentOS or super old Alpine Linux, the dart executable would crash due to incompatibility with super old glibc or musl-libc. In this case, the best thing to do is to upgrade the outdated OS.
2. Rubygems or bundler being too old, or you are using Ruby 3.1 from Debian which is broken out of box. This can cause incorrect version of dart executable to be installed and crash on launch. The solution is to upgrade Rubygems/Bundler, remove Gemfile.lock if exists, and try again. Upgrade or install a separate ruby would also help if you cannot upgrade Rubygems.
